[package]
name = "prover"
version = "1.0.0"
edition = "2018"
authors = ["The ZKM Team"]
homepage = "https://zkm.io/"
repository = "https://github.com/zkMIPS/mips_circuit"
license = "Apache-2.0"
keywords = ["blockchain", "zkm"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
types = { path = "../../lib/types", version = "1.0" }
witness_generator = { path = "../witness_generator", version = "1.0" }
storage = { path = "../../lib/storage", version = "1.0" }
vlog = { path = "../../lib/vlog", version = "1.0" }
config = { path = "../../lib/config", version = "1.0" }
circuit = { path = "../../lib/circuit", version = "1.0" }
tokio = { version = "1", features = ["full"] }
ctrlc = { version = "3.1", features = ["termination"] }
zokrates_ark = { version = "0.1", path = "../../../zokrates_ark", features = ["multicore"], optional = true }
zokrates_common = { version = "0.1", path = "../../../zokrates_common", default-features = false }