[workspace]
resolver = "2"
members = [
    # Binaries
    "",

    # Libraries
    "core/lib/circuit"
]

[profile.release.package.flamegraph_target]
# We need both performance and debug info to analyze.
debug = true