[workspace]
resolver = "2"
members = [
    # Binaries
    "",

    # Libraries
    "core/lib/circuit",
    "core/lib/storage",
    "core/lib/vlog",
    "core/lib/utils",
    "core/lib/basic_types",
    "core/lib/utils_macro_driver",
]