[package]
name = "server"
version = "1.0.0"
edition = "2018"
authors = ["The ZKM Team"]
homepage = "https://zkm.io/"
repository = "https://github.com/zkMIPS/mips_circuit"
license = "Apache-2.0"
keywords = ["blockchain", "zkm"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
witness_generator = { path = "../witness_generator", version = "1.0" }
storage = { path = "../../lib/storage", version = "1.0" }
vlog = { path = "../../lib/vlog", version = "1.0" }
config = { path = "../../lib/config", version = "1.0" }
futures = "0.3"
structopt = "0.3.20"
anyhow = "1.0"
ctrlc = { version = "3.1", features = ["termination"] }
tokio = { version = "1", features = ["full"] }
serde = "1.0.90"

[dev-dependencies]
serde_json = "1.0.0"