[package]
name = "witness_generator"
version = "1.0.0"
edition = "2018"
authors = ["The ZKM Team"]
homepage = "https://zkm.io/"
repository = "https://github.com/zkMIPS/mips_circuit"
license = "Apache-2.0"
keywords = ["blockchain", "zkm"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
types = { path = "../../lib/types", version = "1.0" }
storage = { path = "../../lib/storage", version = "1.0" }
circuit = { path = "../../lib/circuit", version = "1.0" }

utils = { path = "../../lib/utils", version = "1.0" }

vlog = { path = "../../lib/vlog", version = "1.0"}
tracing = "0.1.22"

serde = "1.0.130"
serde_json = "1.0.72"
metrics = "0.17"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
actix-rt = "2.2.0"
actix-web = "4.0.0-beta.8"
actix-web-httpauth = "0.6.0-beta.2"

ctrlc = { version = "3.1", features = ["termination"] }
jsonwebtoken = "7"
anyhow = "1.0"
async-trait = "0.1.42"

[dev-dependencies]
num = { version = "0.3.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["blocking"] }
